import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5', padding: 16 },
  balanceCard: { backgroundColor: '#4a90e2', padding: 20, borderRadius: 12, marginBottom: 20, alignItems: 'center' },
  balanceLabel: { color: '#fff', fontSize: 16, opacity: 0.9 },
  balanceValue: { color: '#fff', fontSize: 32, fontWeight: 'bold', marginTop: 8 },
  totalsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, width: '100%' },
  totalsBadge: { flex: 1, paddingVertical: 12, paddingHorizontal: 14, borderRadius: 12, marginHorizontal: 4 },
  totalsLabel: { color: '#fff', fontSize: 12, marginBottom: 4, opacity: 0.9 },
  totalsValue: { color: '#fff', fontSize: 16, fontWeight: '700' },
  totalsBadgeHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  totalsBadgeIcon: { marginRight: 6 },
  expenseBadge: { backgroundColor: 'rgba(231, 76, 60, 0.25)' },
  incomeBadge: { backgroundColor: 'rgba(46, 204, 113, 0.25)' },
  list: { flexGrow: 1 },
  txItem: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, backgroundColor: '#fff', borderRadius: 8, marginBottom: 8, elevation: 2 },
  txCategoryRow: { flexDirection: 'row', alignItems: 'center' },
  txIcon: { marginRight: 10 },
  txCategory: { fontSize: 16, fontWeight: '500' },
  txDate: { fontSize: 12, color: '#888' },
  txAmount: { fontSize: 18, fontWeight: 'bold' },
  income: { color: '#2ecc71' },
  expense: { color: '#e74c3c' },
  emptyText: { textAlign: 'center', marginTop: 40, color: '#888', fontSize: 16 },
  headerButton: { padding: 8, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.18)', marginRight: 12 },
  addButton: { backgroundColor: '#4a90e2', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  addButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  loadingContainer: { flex: 1, justifyContent: 'center' },
});

export const addTransactionStyles = StyleSheet.create({
  container: { flexGrow: 1, padding: 20, backgroundColor: '#fff' },
  typeToggle: { flexDirection: 'row', marginBottom: 20, borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#ddd' },
  typeBtn: { flex: 1, padding: 12, alignItems: 'center' },
  typeText: { fontSize: 16, fontWeight: '500' },
  activeType: { backgroundColor: '#4a90e2' },
  activeTypeText: { color: '#fff' },
  input: { borderWidth: 1, borderColor: '#ccc', padding: 12, borderRadius: 8, marginBottom: 12, fontSize: 16 },
  dropdown: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#ccc', padding: 12, borderRadius: 8, marginBottom: 12 },
  dropdownText: { fontSize: 16, color: '#333' },
  dropdownArrow: { fontSize: 16, color: '#555' },
  dropdownList: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, marginBottom: 12, backgroundColor: '#fff' },
  dropdownItem: { padding: 12, borderBottomWidth: 1, borderBottomColor: '#eee' },
  dropdownItemRow: { flexDirection: 'row', alignItems: 'center' },
  dropdownItemIcon: { marginRight: 10 },
  dropdownItemText: { fontSize: 16, color: '#333' },
  emptyCategoryText: { color: '#888', padding: 12, fontSize: 14 },
  manageButton: { padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#4a90e2', marginBottom: 12, alignItems: 'center' },
  manageButtonText: { color: '#4a90e2', fontSize: 16, fontWeight: '600' },
  headerButton: { padding: 8, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.18)', marginRight: 12 },
  textArea: { height: 80, textAlignVertical: 'top' },
  saveBtn: { backgroundColor: '#2ecc71', padding: 16, borderRadius: 8, alignItems: 'center', marginTop: 10 },
  saveBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  fullScreen: { flex: 1 },
});

export const categoriesStyles = StyleSheet.create({
  container: { flexGrow: 1, backgroundColor: '#fff', padding: 20 },
  title: { fontSize: 26, fontWeight: 'bold', marginBottom: 16, color: '#333' },
  typeToggle: { flexDirection: 'row', marginBottom: 20, borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#ddd' },
  typeBtn: { flex: 1, padding: 12, alignItems: 'center' },
  typeText: { fontSize: 16, fontWeight: '500', color: '#333' },
  activeType: { backgroundColor: '#4a90e2' },
  activeTypeText: { color: '#fff' },
  input: { borderWidth: 1, borderColor: '#ccc', padding: 12, borderRadius: 8, marginBottom: 12, fontSize: 16 },
  addBtn: { backgroundColor: '#4a90e2', padding: 14, borderRadius: 8, alignItems: 'center', marginBottom: 24 },
  addBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 16 },
  iconOption: { width: 48, height: 48, borderRadius: 12, borderWidth: 1, borderColor: '#ddd', justifyContent: 'center', alignItems: 'center', margin: 6, backgroundColor: '#fff' },
  iconOptionSelected: { backgroundColor: '#4a90e2', borderColor: '#4a90e2' },
  listSection: { marginBottom: 20 },
  sectionTitle: { fontSize: 18, fontWeight: '700', marginBottom: 10, color: '#333' },
  categoryItemRow: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 8, backgroundColor: '#f5f5f5', marginBottom: 8 },
  categoryIcon: { marginRight: 10 },
  categoryText: { fontSize: 16, color: '#333' },
  emptyText: { color: '#888', fontSize: 14 },
  headerButton: { padding: 8, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.18)', marginRight: 12 },
});

export const settingsStyles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: '#f5f5f5', justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 28, fontWeight: 'bold', marginBottom: 12, color: '#333' },
  description: { fontSize: 16, color: '#666', textAlign: 'center', lineHeight: 24 },
});
